apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-k0rdent 
  namespace: backstage-k0rdent 
  labels:
    app: backstage-k0rdent 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-k0rdent
  template:
    metadata:
      labels:
        app: backstage-k0rdent
    spec:
      serviceAccountName: backstage-health-plugin 
      containers:
        - name: backstage-k0rdent
          image: ghcr.io/barelyanxer/backstage:test
          imagePullPolicy: Always
          ports:
            - containerPort: 7007
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: APP_BASE_URL
              value: "http://a3dc41ef5af8b4a45aa1439559414c53-954582395.us-west-2.elb.amazonaws.com"
            - name: BACKEND_BASE_URL
              value: "http://a3dc41ef5af8b4a45aa1439559414c53-954582395.us-west-2.elb.amazonaws.com"
            - name: BACKEND_CORS_ORIGIN
              value: "http://a3dc41ef5af8b4a45aa1439559414c53-954582395.us-west-2.elb.amazonaws.com"
            - name: CAPI_VISUALIZER_URL
              value: "http://a1bb4a222eed343b580e90dedd41d3e9-1453544455.us-west-2.elb.amazonaws.com:8081"