apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-k0rdent 
  namespace: backstage-k0rdent 
  labels:
    app: backstage-k0rdent 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-k0rdent
  template:
    metadata:
      labels:
        app: backstage-k0rdent
    spec:
      containers:
        - name: backstage-k0rdent
          image: ghcr.io/barelyanxer/backstage:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7007
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: APP_BASE_URL
              value: "http://SERVICE_EXTERNAL_IP"
            - name: BACKEND_BASE_URL
              value: "http://SERVICE_EXTERNAL_IP"
            - name: BACKEND_CORS_ORIGIN
              value: "http://SERVICE_EXTERNAL_IP"
            - name: CAPI_VISUALIZER_URL
              value: "http://YOUR_CAPI_URL:8081"