kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30007 # This MUST match the 'nodePort' you specified in your Service YAML.
    hostPort: 7007       # The port you want to use on your host machine (localhost).
    listenAddress: "0.0.0.0" # Or "127.0.0.1"
    protocol: TCP