apiVersion: v1
kind: Service
metadata:
  name: opencost-service
  namespace: opencost
spec:
  selector:
    app: opencost
  ports:
    - protocol: TCP
      port: 9003       # Port exposed externally
      targetPort: 9003 # Port inside the pod
  type: LoadBalancer
